uat_pay_db:
  host: 10.91.19.100
  port: 3324
  user: ldyop
  passwd: Ldyop123@ldygo.com

uat_cus_db:
  host: 10.91.19.100
  port: 3321
  user: ldyop
  passwd: Ldyop123@ldygo.com

pre_pay_db:
  host: 10.90.16.109
  port: 3324
  user: ldyop
  passwd: Ldyop123@ldygo.com

pre_cus_db:
  host: 10.90.16.109
  port: 3321
  user: ldyop
  passwd: Ldyop123@ldygo.com

ex_pay_db:
  host: 10.60.80.94
  port: 3311
  user: ldyop
  passwd: Ldyop123@ldygo.com

ex_cus_db:
  host: 10.60.80.94
  port: 3311
  user: ldyop
  passwd: Ldyop123@ldygo.com